version: "3"

volumes:
  postgres_db: {}

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=dlit_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=[DB PASSWORD]
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env-file:
      - ./.env
    volumes:
      - ./static:/staticfiles
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
