version: "3"
services:
  django:
    build: .
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./static:/staticfiles
    command: python manage.py runsslserver --certificate django.crt --key django.key
