version: "3"

volumes:
  postgres_db: {}


services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=[DB NAME]
      - POSTGRES_USER=[DB USERNAME]
      - POSTGRES_PASSWORD=[DB PASSWORD]
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./static:/staticfiles

    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=
      - DJANGO_ALLOWED_HOST=localhost 127.0.0.1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=blit_db
      - SQL_USER=
      - SQL_PASSWORD=
      - SQL_HOST=db
      - SQL_PORT=5432
