version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./static:/staticfiles
    command: gunicorn config.wsgi --bind 0.0.0.0:8000

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./django.crt:/etc/nginx/certs/django.crt
      - ./django.key:/etc/nginx/certs/django.key
    depends_on:
      - web
