version: "3"

volumes:
  postgres_db: {}

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=dlit_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=[DB PASSWORD]
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./static:/staticfiles
    environment:
      - SECRET_KEY=
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - SQL_DATABASE=blit_db
      - SQL_USER=admin
      - SQL_PASSWORD=
      - AZURE_BING_SEARCH_API_KEY=
      - CLOVA_API_URL=
      - CLOVA_API_KEY=
