version: "3"

volumes:
  postgres_db: {}

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=blit_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - web.env
    volumes:
      - ./static:/staticfiles
    command: gunicorn config.wsgi --bind 0.0.0.0:80
