# Generated by Django 4.1.7 on 2023-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="tag",
            field=models.ManyToManyField(blank=True, to="image.tag"),
        ),
    ]
