# Generated by Django 4.1.7 on 2023-06-28 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="attendants",
            field=models.ManyToManyField(
                null=True, related_name="meetings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_code",
            field=models.TextField(unique=True),
        ),
    ]
