# Generated by Django 4.1.7 on 2023-06-30 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="attendants",
            field=models.ManyToManyField(
                blank=True, related_name="meetings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="attendants",
            field=models.ManyToManyField(
                blank=True, related_name="rounds", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
