# Generated by Django 4.1.7 on 2023-06-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0002_alter_meeting_attendants_alter_meeting_meeting_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
