# Generated by Django 4.1.7 on 2023-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_kakao_pay_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kakao_name",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
